AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BmcApp

Parameters:

  RailsEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production

Globals:

  Function:
    Architectures:
      - x86_64
    AutoPublishAlias: live
    DeploymentPreference:
      Type: AllAtOnce
    Environment:
      Variables:
        RAILS_ENV: !Ref RailsEnv
        DATABASE_URL: x-crypteia-ssm:/database_url
    Timeout: 30

Resources:

  RailsLambdaBmc:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
      DockerTag: web
    Properties:
      FunctionUrlConfig:
        AuthType: NONE
      MemorySize: 1792
      PackageType: Image
      Policies:
        - Statement:
          - Effect: Allow
            Action: ["ssm:Get*", "ssm:Describe*"]
            Resource:
              - !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/*
Outputs:

  RailsLambdaBmcUrl:
    Description: BMC Rails app lambda
    Value: !GetAtt RailsLambdaBmcUrl.FunctionUrl
